import Motor
import RPi.GPIO as GPIO

GPIO.setmode(GPIO.BOARD)
GPIO.setwarnings(False)

def forward():
    GPIO.output(Motor.motor_front_right.in1, GPIO.HIGH)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def down():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.HIGH)
def left():
    GPIO.output(Motor.motor_front_right.in1, GPIO.HIGH)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.HIGH)
def right():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def stop():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def forward_right():
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def forward_left():
    GPIO.output(Motor.motor_front_right.in1, GPIO.HIGH)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
def down_right():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
def down_left():
    GPIO.output(Motor.motor_front_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.HIGH)
def right_around():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.HIGH)
def left_around():
    GPIO.output(Motor.motor_front_right.in1, GPIO.HIGH)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def left_rotate():
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.HIGH)
def right_rotate():
    GPIO.output(Motor.motor_back_left.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def rightN():
    GPIO.output(Motor.motor_front_right.in1, GPIO.HIGH)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in1,GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)
def leftN():
    GPIO.output(Motor.motor_front_right.in1, GPIO.LOW)
    GPIO.output(Motor.motor_front_right.in2, GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_front_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_left.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_left.in2, GPIO.HIGH)
    GPIO.output(Motor.motor_back_right.in1,GPIO.LOW)
    GPIO.output(Motor.motor_back_right.in2, GPIO.LOW)